### ISSUE TITLE
iOS Linking issue

### ISSUE THREAD

**Issue by makedirectory** [react-native-community/voice#170]
After following the instructions for manually linking the library via xCode I receive this error:

In file included from /Users/username/Documents/Applications/app/node_modules/react-native-voice/ios/Voice/Voice.m:1:
/Users/username/Documents/Applications/app/node_modules/react-native-voice/ios/Voice/Voice.h:1:9: fatal error: 'React/RCTBridgeModule.h' file not found

#import <React/RCTBridgeModule.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~

1 error generated.

---
I've searched online and in the forms and haven't had any luck. Maybe I am missing something small? Or is this a new issue?

All my other libraries are linked via my Podfile...

Thanks! Working great on Android!

Update: Success with a fresh project/install and no Podfile.

**Comment by makedirectory** [comment]
Added a podspec file, happy to make a PR

Cheers,
Andrew

**Comment by lfoliveir4** [comment]
> Added a podspec file, happy to make a PR
> 
> Cheers,
> Andrew
> 
> require 'json'
> version = JSON.parse(File.read('package.json'))["version"]
> 
> Pod::Spec.new do |s|
> s.name = "react-native-voice"
> s.version = version
> s.summary = "![alt tag]"
> s.homepage = "https://github.com/wenkesj/react-native-voice"
> s.license = "MIT"
> s.author = "Sam Wenke"
> s.platform = :ios, "9.0"
> s.source = { :git => "https://github.com/wenkesj/react-native-voice.git", :tag => "v#{s.version}" }
> s.source_files = 'ios/Voice/_.{h,m}' s.preserve_paths = "**/_.js"
> s.dependency 'React'
> 
> end

@makedirectory Did you solve your problem?

**Comment by juakotorres** [comment]
I added this to the Podfile:

`pod 'react-native-voice', :path => '../node_modules/react-native-voice/react-native-voice.podspec'`

It worked for me.

**Comment by Naturalclar** [comment]
Seems like this issue can be closed, as podspec for react-native-voice has already been added to the repo
