### ISSUE TITLE
Any alternative for this lib?

### ISSUE THREAD

**Issue by B4ckes** [react-native-community/voice#216]
As i can see this library looks kind of abandoned, and it's not working for me, does anyone know an alternative library?

**Comment by lfoliveir4** [comment]
@B4ckes What problem is going on with you?

**Comment by raygerrard** [comment]
Also cannot get this working anymore. After installing and running react-native link and importing in my javascript I get the error Native module cannot be null.

**Comment by Gustavo-Kuze** [comment]
@lfoliveir4  If we create a new React Native app specifying version to 0.54.7 (the exact version of the [demo](https://github.com/react-native-community/react-native-voice/blob/master/VoiceTest/package.json) app) it works as expected on Android, but I wasn't able to compile/install the app on current version of react-native (0.61.5) after installing this package, the same problem as @raygerrard pointed. Are there any plans to update the lib so It can work again on current version as well?

**Comment by Sumit-Chakole** [comment]
I too have exact same issue described by @raygerrard. Lib was working absolutely fine in with rn 0.59.10. However after I upgrade project to rn 0.61.4, its throwing exactly same issue as described by @raygerrard . @raygerrard and @Gustavo-Kuze : Did you find resolution for this? Do you found any alternative?

**Comment by safaiyeh** [comment]
Hello all, @Naturalclar and I are the new maintainers for this repo. We are working to clean up and bringing it back to life.

Closing as it is maintained now. @Sumit-Chakole could you create a separate issue to support the latest RN version.
