### ISSUE TITLE
Is this service available on devices without Google Services?

### ISSUE THREAD

**Issue by Aung-Myint-Thein** [react-native-community/voice#230]
Thanks for the simple and great library. I am using this library and working pretty fine. Recently I tested on a device without Google Service and it is not working. So, I would like to confirm if this library needs Google Service to run?

**Comment by safaiyeh** [comment]
I do not see any dependencies with Google Services. Do you have a log of your errors or a repo so I can debug?

**Comment by jamsch** [comment]
You'd currently need the [Google App](https://play.google.com/store/apps/details?id=com.google.android.googlequicksearchbox&hl=en) (installed from the Play Store) to use speech recognition on Android. You'd need to set "RECOGNIZER_ENGINE" to a recognition engine that's supported on the device (`Voice.start(locale, { RECOGNIZER_ENGINE: "..." })`).

**Comment by safaiyeh** [comment]
Thanks for the context @jamsch. I do not believe we have that documented here. Do you mind making a PR?

**Comment by Aung-Myint-Thein** [comment]
> You'd currently need the [Google App](https://play.google.com/store/apps/details?id=com.google.android.googlequicksearchbox&hl=en) (installed from the Play Store) to use speech recognition on Android.
> 
> Otherwise you could look in to setting the "RECOGNIZER_ENGINE" to a recognition engine that's supported on the Android device -- e.g. `Voice.start(locale, { RECOGNIZER_ENGINE: "..." })`

In one of the device, I have the output of 
`Voice.getSpeechRecognitionServices()` ==> `["com.xiaomi.mibrain.speech"]` and voice recognising is not working.
`Voice.start()` ==> `undefined` but
`Voice.isAvailable()` ==> `true`
`Voice.isRecognizing()` ==> `true`

but none of the following events are triggered,
```
Voice.onSpeechResults
Voice.onSpeechStart
Voice.onSpeechEnd
Voice.onSpeechError
Voice.onSpeechPartialResults
```

I tried again after installing Google App and now the device returns `["com.google.android.googlequicksearchbox", "com.xiaomi.mibrain.speech"]` for `Voice.getSpeechRecognitionServices()` but voice is still not working. Permission is granted and I can record and play using `@react-native-community/audio-toolkit`. 

How should I set the `RECOGNIZER_ENGINE`? Any suggestions and recommendations? Thanks!

**Comment by Aung-Myint-Thein** [comment]
I found out something which might be useful for fellow developers. Even after all the permissions are correct in Android, there is one last thing to make sure this library is working fine on Android. Please make sure the device has Google Speech Recognizing Engine such as `com.google.android.googlequicksearchbox` by calling `Voice.getSpeechRecognitionServices()`. Since Android phones can be configured with so many options, even if a device has googlequicksearchbox engine, it could be configured to use other services. You can check which service is used for Voice Assistive App in following steps for most Android phones:

Settings > App Management > Default App > Assistive App and Voice Input > Assistive App

Happy to contribute into one of the proper sections in Readme if this is helpful and useful for developers.

**Comment by safaiyeh** [comment]
It would be helpful to document this @Aung-Myint-Thein

**Comment by Aung-Myint-Thein** [comment]
Btw, would be nice if someone with `RECOGNIZER_ENGINE` can add in documentation or point to where we should look at. @safaiyeh @jamsch

**Comment by victor012888** [comment]
Excuse me, is this Issue mean this packge can works without google service right?
