### ISSUE TITLE
Recognising wrong output and also "onSpeechPartialResults" is returning only 1 word in array

### ISSUE THREAD

**Issue by Nehal-29** [react-native-community/voice#232]
Scenario: I've two options a) female b) male

Everytime I say male it returns "Mail". Is there anyway where I can get all the similar results which sound like male/mail from this library?

@wenkesj @lucianomlima

**Comment by Nehal-29** [comment]
In Android, partial results returns all the words of similar sound but not in the case of iOS

**Comment by lucianomlima** [comment]
Sorry, I never used this lib on RN.

**Comment by safaiyeh** [comment]
Hello @Nehal-29! Could you provide a reproducible demo, either another repo or in the example app so I can test it out?
