### ISSUE TITLE
Release new Version on npm

### ISSUE THREAD

**Issue by DanielBoening** [react-native-community/voice#237]
Hello,

is there a reason that on GitHub the relase 1.1.0 is online but on npm it is still version 0.3.0?

**Comment by jamsch** [comment]
Package updates are now being updated under 
[@react-native-community/voice](https://www.npmjs.com/package/@react-native-community/voice)

**Comment by DanielBoening** [comment]
Thanks for the fast answer. The readme should be updated as the badge still points to the old npm package.

**Comment by Naturalclar** [comment]
Will be fixed with #238
