### ISSUE TITLE
isAvailable is always false 

### ISSUE THREAD

**Issue by victor012888** [react-native-community/voice#267]
Dear community,

I have some problem about this packge
My code is like this 
`  onPress={async () => {
            console.log(await Voice.isAvailable());
          }} `
the console.log is always false

I'm not sure which part goes wrong
But when I use other packge need microphone(like react-native-community/audio-toolkit)works well
so it should not be microphone and access's problem

here's some packge version may be relative(if anything left,I'll add it later
`"react": "16.11.0",
    "react-native": "0.62.2",
    "@react-native-community/voice": "^1.1.3",`

thanks a lot

**Comment by jimdog1001** [comment]
hi victor, did you find the solution? i am having the same problem
